CREATE TABLE DWH_Project.fact_flight (
    passanger_key INT64,
    passanger_profile_key INT64,
    aircraft_key INT64,
    fare_basis_key INT64,
    crew_key INT64,
    origin_airport_key INT64,
    destination_airport_key INT64,
    departure_date_key INT64,
    arrival_date_key INT64,
    ticket_number STRING,
    fare_paid NUMERIC,
    overnight_stays INT64,
    revenue NUMERIC,
    luggage_fees NUMERIC,
    upgrade_fees NUMERIC,
    services_fees NUMERIC,
    departure_time TIMESTAMP,
    arrival_time TIMESTAMP
);
